// auth.js
export const FETCH_AUTH_USER = 'FETCH_USER'
export const UPDATE_AUTH_USER = 'UPDATE_AUTH_USER'
export const UPDATE_AUTH_KEY = 'UPDATE_AUTH_KEY'
export const UPDATE_AUTH_MODEL = 'UPDATE_AUTH_MODEL'

// status.js
export const UPDATE_MENU_MODAL_STATUS = 'UPDATE_MENU_MODAL_STATUS'
